server:
  AppMode: "release"
  HttpPort: ":3000"
  JwtKey: "your key"

database:
  Db: "mysql"
  DbHost: "localhost"
  DbPort: 3306
  DbUser: "root"
  DbPassWord: "root"
  Dbname: "geollm"
  MaxOpenConns: 20
  MaxIdleConns: 10

ocr:
  OcrApi: "your api"

eva:
  EvaApi: "your api"

minio:
  Endpoint: "127.0.0.1:9000"
  AccessKeyID: "minioadmin"
  SecretAccessKey: "minioadmin"
  RawQuality: 50
  ThumbnailQuality: 10
  UseSSL: false