name: CI

on:
  push:
    branches:
      - main # 触发工作流的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t d1caprio/geollm:${{ github.sha }} .
          docker tag d1caprio/geollm:${{ github.sha }} d1caprio/geollm:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push d1caprio/geollm:latest
          docker push d1caprio/geollm:${{ github.sha }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker pull d1caprio/geollm:${{ github.sha }}
            docker stop geollm || true  
            docker rm geollm || true   
            docker run -d --name geollm -p 3000:3000 d1caprio/geollm:${{ github.sha }}